// nomor panggilan darurat
export const NOMOR_DARURAT = {
  '110': 'Polisi',
  '112': 'Layanan Darurat',
  '113': 'Pemadam Kebakaran',
  '115': 'SAR',
  '118': 'Ambulans',
};

// Daftar prefix untuk nomor telepon
export const PREFIX_TELEPON = {
  '021': [
    'Jakarta',
    'Tangerang',
    'Tangerang Selatan',
    'Bekasi',
    'Depok',
    'Kabupaten Bogor',
  ],
  '022': ['Bandung', 'Cimahi'],
  '0231': ['Cirebon'],
  '0232': ['Kuningan'],
  '0233': ['Majalengka'],
  '0234': ['Indramayu'],
  '024': ['Kota Semarang', 'Kabupaten Semarang'],
  '0251': ['Kota Bogor', 'Sawangan', 'Kabupaten Bogor'],
  '0252': ['Lebak'],
  '0253': ['Pandeglang'],
  '0254': ['Cilegon', 'Serang'],
  '0260': ['Subang'],
  '0261': ['Sumedang'],
  '0262': ['Garut'],
  '0263': ['Cianjur'],
  '0264': ['Purwakarta'],
  '0265': ['Banjar', 'Ciamis', 'Tasikmalaya'],
  '0266': ['Sukabumi'],
  '0267': ['Karawang'],
  '0271': ['Surakarta', 'Sragen', 'Karanganyar', 'Sukoharjo', 'Boyolali'],
  '0272': ['Klaten'],
  '0273': ['Wonogiri'],
  '0274': ['Yogyakarta'],
  '0275': ['Purworejo'],
  '0276': ['Boyolali'],
  '0280': ['Cilacap'],
  '0281': ['Banyumas', 'Purbalingga'],
  '0282': ['Cilacap'],
  '0283': ['Tegal', 'Brebes'],
  '0284': ['Pemalang'],
  '0285': ['Pekalongan', 'Batang'],
  '0286': ['Banjarnegara', 'Wonosobo'],
  '0287': ['Kebumen'],
  '0289': ['Bumiayu'],
  '0291': ['Kudus', 'Jepara'],
  '0292': ['Grobogan'],
  '0293': ['Magelang', 'Temanggung'],
  '0294': ['Kendal', 'Gringsing'],
  '0295': ['Pati', 'Rembang'],
  '0296': ['Blora'],
  '0297': ['Karimun Jawa'],
  '0298': ['Salatiga', 'Kabupaten Semarang', 'Boyolali'],
  '031': ['Surabaya', 'Gresik', 'Sidoarjo', 'Bangkalan'],
  '0321': ['Mojokerto', 'Jombang'],
  '0322': ['Lamongan'],
  '0323': ['Sampang'],
  '0324': ['Pamekasan'],
  '0325': ['Bawean'],
  '0326': ['Kepulauan Masalembu'],
  '0327': ['Kangean'],
  '0328': ['Sumenep'],
  '0331': ['Jember'],
  '0332': ['Bondowoso'],
  '0333': ['Banyuwangi'],
  '0334': ['Lumajang'],
  '0335': ['Probolinggo'],
  '0336': ['Jember'],
  '0338': ['Situbondo'],
  '0341': ['Malang', 'Batu'],
  '0342': ['Blitar'],
  '0343': ['Pasuruan'],
  '0351': ['Madiun', 'Magetan', 'Ngawi'],
  '0352': ['Ponorogo'],
  '0353': ['Bojonegoro'],
  '0354': ['Kediri'],
  '0355': ['Tulungagung', 'Trenggalek'],
  '0356': ['Tuban'],
  '0357': ['Pacitan'],
  '0358': ['Nganjuk'],
  '0361': ['Denpasar', 'Badung', 'Gianyar', 'Tabanan'],
  '0362': ['Buleleng'],
  '0363': ['Karangasem'],
  '0365': ['Jembrana'],
  '0366': ['Klungkung', 'Bangli'],
  '0368': ['Baturiti', 'Bedugul'],
  '0370': ['Mataram', 'Lombok Barat', 'Lombok Tengah'],
  '0371': ['Sumbawa'],
  '0372': ['Sumbawa Barat'],
  '0373': ['Dompu'],
  '0374': ['Bima'],
  '0376': ['Lombok Timur'],
  '0379': ['Kepulauan Alor'],
  '0380': ['Kupang'],
  '0381': ['Ende'],
  '0382': ['Sikka'],
  '0383': ['Flores Timur'],
  '0384': ['Ngada'],
  '0385': ['Manggarai'],
  '0386': ['Manggarai Barat'],
  '0387': ['Sumba'],
  '0388': ['Timor Tengah Utara', 'Timor Tengah Selatan'],
  '0389': ['Belu'],
};

// Daftar prefix nomor telepon seluler
export const PREFIX_SELULER = {

};

// Daftar wilayah untuk satu kode area
export const AREA_WILAYAH = {
  2: [
    'Jakarta',
    'Tangerang',
    'Tangerang Selatan',
    'Bekasi',
    'Depok',
    'Kabupaten Bogor',
    'Bandung',
    'Cimahi',
    'Cirebon',
    'Kuningan',
    'Majalengka',
    'Indramayu',
    'Kota Semarang',
    'Kabupaten Semarang',
    'Kota Bogor',
    'Sawangan',
    'Lebak',
    'Pandeglang',
    'Cilegon',
    'Serang',
    'Subang',
    'Sumedang',
    'Garut',
    'Cianjur',
    'Purwakarta',
    'Banjar',
    'Ciamis',
    'Tasikmalaya',
    'Sukabumi',
    'Karawang',
    'Surakarta',
    'Sragen',
    'Karanganyar',
    'Sukoharjo',
    'Boyolali',
    'Klaten',
    'Wonogiri',
    'Yogyakarta',
    'Purworejo',
    'Boyolali',
    'Cilacap',
    'Banyumas',
    'Purbalingga',
    'Tegal',
    'Brebes',
    'Pemalang',
    'Pekalongan',
    'Batang',
    'Banjarnegara',
    'Wonosobo',
    'Kebumen',
    'Bumiayu',
    'Kudus',
    'Jepara',
    'Grobogan',
    'Magelang',
    'Temanggung',
    'Kendal',
    'Gringsing',
    'Pati',
    'Rembang',
    'Blora',
    'Karimun Jawa',
    'Salatiga',
    'Boyolali',
  ],
  3: [
    'Surabaya', 'Gresik', 'Sidoarjo', 'Bangkalan',
    'Mojokerto',
    'Jombang',
    'Lamongan',
    'Sampang',
    'Pamekasan',
    'Bawean',
    'Kepulauan Masalembu',
    'Kangean',
    'Sumenep',
    'Jember',
    'Bondowoso',
    'Banyuwangi',
    'Lumajang',
    'Probolinggo',
    'Situbondo',
    'Malang',
    'Batu',
    'Blitar',
    'Pasuruan',
    'Madiun',
    'Magetan',
    'Ngawi',
    'Ponorogo',
    'Bojonegoro',
    'Kediri',
    'Tulungagung',
    'Trenggalek',
    'Tuban',
    'Pacitan',
    'Nganjuk',
    'Denpasar',
    'Badung',
    'Gianyar',
    'Tabanan',
    'Buleleng',
    'Karangasem',
    'Jembrana',
    'Klungkung',
    'Bangli',
    'Baturiti',
    'Bedugul',
    'Mataram',
    'Lombok Barat',
    'Lombok Tengah',
    'Sumbawa',
    'Sumbawa Barat',
    'Dompu',
    'Bima',
    'Lombok Timur',
    'Kepulauan Alor',
    'Kupang',
    'Ende',
    'Sikka',
    'Flores Timur',
    'Ngada',
    'Manggarai',
    'Manggarai Barat',
    'Sumba',
    'Timor Tengah Utara',
    'Timor Tengah Selatan',
    'Belu',
  ],
};
