name: Lint the files to ensure code quality

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Connect workflow to repository
        uses: actions/checkout@v2
      - name: Install all required dependencies
        run: yarn install --frozen-lockfile
      - name: Lint and test the files
        run: yarn lint & yarn test
