name: Lint the files to ensure code quality

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Connect workflow to repository
        uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.7.1
      - name: Install all required dependencies
        run: pnpm install
      - name: Lint and test the files
        run: pnpm run lint & pnpm run test
