name: Publish to NPM for each push to master and pull request (canary)

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - name: Checkout to repository
        uses: actions/checkout@v2
      - run: git fetch --unshallow --tags
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.7.1
      - name: Install dependencies
        run: pnpm install
      - name: Lint and test the files
        run: pnpm run lint:fix & pnpm run test
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          pnpm build
          pnpx auto shipit

